version: "3.3"

services:
  apache:
    build: ./
    container_name: 'myzip'
    restart: 'always'
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Jakarta"
    volumes:
      - ./myzip:/var/www/html
      - ./php:/usr/local/etc/php/php.ini
      - ./apache-logs:/var/log/apache2
      - ./apache2/sites-available:/etc/apache2/sites-available
    networks:
        my_net:
          ipv4_address: 172.30.1.2

networks:
    my_net:
        ipam:
            driver: default
            config:
                - subnet: 172.30.0.0/16