pipline {
    
    agent any

    stage {
        
        stage("build"){
            steps {
                echo 'building the application'
            }
        
        }
        stage("test"){
            steps {
                echo 'testing the application'
            }
        }
        stage("deploy"){
            steps {
                echo 'building the application'
            }
        }
    }
}